### ISSUE TITLE
Add Pins to the BC Campus Map

### ISSUE THREAD

**Issue by TheLoneJohn** [5donuts/mapper#23]
Currently waiting on node points

**Comment by 5donuts** [comment]
There should be pins specifically for buildings on the map, specified from somewhere in the database.
We'll have to meet to discuss exactly how we plan on storing/collecting that information.

**Comment by 5donuts** [comment]
You can just use the `Graph.getDestinationPins()` and `Graph.getPolylines(GoogleMap)` methods to get the node points.
At the moment, there are none in the database, but once the JSON stuff is finished there will be.
